### ISSUE TITLE
rstan (and packages that are downstream from it)

### ISSUE THREAD

**Issue by bgoodri** [r-windows/r-testing#1]
If you were to attempt to install or check the **rstan** package version 2.18.x under R-testing, it will fail with
```
> install.packages("rstan", INSTALL_opts = "--no-multiarch")
Installing package into ‘C:/Users/Stan/Documents/R/win-library/testing’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/rstan_2.18.2.tar.gz'
Content type 'application/x-gzip' length 838052 bytes (818 KB)
downloaded 818 KB

* installing *source* package 'rstan' ...
** package 'rstan' successfully unpacked and MD5 sums checked
** libs
Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined
```
In my opinion, R-testing should be defining CXX14 and CXX17 in `src/gnuwin32/fixed/etc/Makeconf` because those standards are supported by rtools40. 

As a temporary workaround, you could first execute
```
dir.create("~/.R",  showWarnings = FALSE)
cat("CXX14 = g++ -std=gnu++14 -m$(WIN)", file = "~/.R/Makevars.win",  append = TRUE)
```
The same error will occur with about 60 packages that are downstream of **rstan**.

**Comment by jeroen** [comment]
Transferred this issue to r-testing. Do you want to write a patch and add it to https://github.com/r-windows/r-testing/blob/master/PKGBUILD#L64-L69 ?

**Comment by bgoodri** [comment]
The CRAN windows servers do define CXX14 = g++ (but probably not CXX17) and CXX14STD = -std=gnu++1y, although they are not defined in the Windows binaries that people download from CRAN. I will make a PR to add them to r-testing.
