### ISSUE TITLE
Version of PKGBUILD for 64bit only

### ISSUE THREAD

**Issue by aadler** [r-windows/r-testing#8]
Hi, @jeroen.

Is there a fundemental difference between modifying PKGBUILD and cobbling a shell-script together to build just the 64-bit version? If so, can you give me some pointers on how I could modify your PKGBUILD to be 64-bit only, please?

**Comment by aadler** [comment]
For the record, since I'm not using PKGBUILD, and so not invoking `makepkg-mingw`, I am running the shell scripts in the MINGW64 shell and **not** the MSYS2 shell.

**Comment by aadler** [comment]
No progress. No need to keep issue open :(

**Comment by jeroen** [comment]
Did you try the `quick-build` script as described in the readme? The `PKGBUILD` is meant to build the full installer, which includes both 32 and 64 bit and all documentation and everything.

**Comment by aadler** [comment]
Yes. I then updated it to build more completely. I was concerned if I'm correct that since I'm not invoking `makepkg-mingw` I should be using the MINGW64 shell and not the MSYS2 shell.

**Comment by jeroen** [comment]
No that doesn't matter at all. The shells are the same, except for the default PATH.
